### ISSUE TITLE
typo in ubuntu.pp

### ISSUE THREAD

**Issue by zonArt** [LStuker/puppet-latex#1]
Hi,

Thanks for your module, I had a look to inspire for my own module and noticed you have a typo in your ubuntu.pp (line 3, "packae").

**Comment by LStuker** [comment]
Hi zonArt

I totally missed your issue request. I am sorry for that and I want to thank you for your hint.
Just that you are informed, I rewrote the module yesterday, but it is not tested yet.

Your input is alway welcome.
